openapi: 3.0.3
info:
  title: "INPUT-003 API"
  version: "1.0.0"

paths:
  /api/v1/register:
    post:
      summary: Register User
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  format: email
                raw_bio:
                  type: string
      responses:
        '200':
          description: OK

