openapi: 3.0.3
info:
  title: "DATA-002 API"
  version: "1.0.0"

paths:
  /api/v1/users/{id}:
    get:
      summary: Get User Details
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  username:
                    type: string
                  password_hash:
                    type: string
                  ssn:
                    type: string

