openapi: 3.0.3
info:
  title: "INPUT-002 API"
  version: "1.0.0"

paths:
  /api/v1/search:
    post:
      summary: Search Records
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                query:
                  type: string
      responses:
        '200':
          description: OK

